FROM golang:1.19 AS build-env
ENV GO111MODULE=off
RUN mkdir -p /go/src/go/
COPY ./valeo/ /go/src/go/valeo/
RUN cd /go/src/go/valeo/internal/cmd/scan && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main